// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.maxsam.proto;

public final class Pingpong {
  private Pingpong() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pingpong.proto\"\027\n\004Ping\022\017\n\007message\030\001 \002(" +
      "\t\"\027\n\004Pong\022\017\n\007message\030\001 \002(\t\"V\n\013RequestInf" +
      "o\022\021\n\trequestId\030\001 \002(\005\022\016\n\006failed\030\002 \002(\010\022\021\n\t" +
      "cancelled\030\003 \002(\010\022\021\n\terrorText\030\004 \002(\t\"T\n\016Se" +
      "rviceMessage\022\023\n\013methodIndex\030\001 \002(\005\022\034\n\006sta" +
      "tus\030\002 \002(\0132\014.RequestInfo\022\017\n\007payload\030\003 \002(\014" +
      "2J\n\017PingPongService\022\030\n\010SendPing\022\005.Ping\032\005" +
      ".Pong\022\035\n\tHeartBeat\022\005.Ping\032\005.Pong(\0010\001B\027\n\020" +
      "com.maxsam.protoP\001\210\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ping_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_Pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pong_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestInfo_descriptor,
        new java.lang.String[] { "RequestId", "Failed", "Cancelled", "ErrorText", });
    internal_static_ServiceMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ServiceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceMessage_descriptor,
        new java.lang.String[] { "MethodIndex", "Status", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
