// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.maxsam.proto;

public interface ServiceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 methodIndex = 1;</code>
   * @return Whether the methodIndex field is set.
   */
  boolean hasMethodIndex();
  /**
   * <code>required int32 methodIndex = 1;</code>
   * @return The methodIndex.
   */
  int getMethodIndex();

  /**
   * <code>required .RequestInfo status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .RequestInfo status = 2;</code>
   * @return The status.
   */
  com.maxsam.proto.RequestInfo getStatus();
  /**
   * <code>required .RequestInfo status = 2;</code>
   */
  com.maxsam.proto.RequestInfoOrBuilder getStatusOrBuilder();

  /**
   * <code>required bytes payload = 3;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>required bytes payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
