// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.maxsam.pingpong.proto;

/**
 * Protobuf service {@code PingPongService}
 */
public  abstract class PingPongService
    implements com.google.protobuf.Service {
  protected PingPongService() {}

  public interface Interface {
    /**
     * <code>rpc SendPing(.Ping) returns (.Pong);</code>
     */
    public abstract void sendPing(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request,
        com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done);

    /**
     * <code>rpc HeartBeat(stream .Ping) returns (stream .Pong);</code>
     */
    public abstract void heartBeat(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request,
        com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new PingPongService() {
      @java.lang.Override
      public  void sendPing(
          com.google.protobuf.RpcController controller,
          com.maxsam.pingpong.proto.Ping request,
          com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done) {
        impl.sendPing(controller, request, done);
      }

      @java.lang.Override
      public  void heartBeat(
          com.google.protobuf.RpcController controller,
          com.maxsam.pingpong.proto.Ping request,
          com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done) {
        impl.heartBeat(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sendPing(controller, (com.maxsam.pingpong.proto.Ping)request);
          case 1:
            return impl.heartBeat(controller, (com.maxsam.pingpong.proto.Ping)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.maxsam.pingpong.proto.Ping.getDefaultInstance();
          case 1:
            return com.maxsam.pingpong.proto.Ping.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.maxsam.pingpong.proto.Pong.getDefaultInstance();
          case 1:
            return com.maxsam.pingpong.proto.Pong.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc SendPing(.Ping) returns (.Pong);</code>
   */
  public abstract void sendPing(
      com.google.protobuf.RpcController controller,
      com.maxsam.pingpong.proto.Ping request,
      com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done);

  /**
   * <code>rpc HeartBeat(stream .Ping) returns (stream .Pong);</code>
   */
  public abstract void heartBeat(
      com.google.protobuf.RpcController controller,
      com.maxsam.pingpong.proto.Ping request,
      com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.maxsam.pingpong.proto.Pingpong.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sendPing(controller, (com.maxsam.pingpong.proto.Ping)request,
          com.google.protobuf.RpcUtil.<com.maxsam.pingpong.proto.Pong>specializeCallback(
            done));
        return;
      case 1:
        this.heartBeat(controller, (com.maxsam.pingpong.proto.Ping)request,
          com.google.protobuf.RpcUtil.<com.maxsam.pingpong.proto.Pong>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.maxsam.pingpong.proto.Ping.getDefaultInstance();
      case 1:
        return com.maxsam.pingpong.proto.Ping.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.maxsam.pingpong.proto.Pong.getDefaultInstance();
      case 1:
        return com.maxsam.pingpong.proto.Pong.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.maxsam.pingpong.proto.PingPongService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sendPing(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request,
        com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.maxsam.pingpong.proto.Pong.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.maxsam.pingpong.proto.Pong.class,
          com.maxsam.pingpong.proto.Pong.getDefaultInstance()));
    }

    public  void heartBeat(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request,
        com.google.protobuf.RpcCallback<com.maxsam.pingpong.proto.Pong> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.maxsam.pingpong.proto.Pong.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.maxsam.pingpong.proto.Pong.class,
          com.maxsam.pingpong.proto.Pong.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.maxsam.pingpong.proto.Pong sendPing(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request)
        throws com.google.protobuf.ServiceException;

    public com.maxsam.pingpong.proto.Pong heartBeat(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.maxsam.pingpong.proto.Pong sendPing(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request)
        throws com.google.protobuf.ServiceException {
      return (com.maxsam.pingpong.proto.Pong) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.maxsam.pingpong.proto.Pong.getDefaultInstance());
    }


    public com.maxsam.pingpong.proto.Pong heartBeat(
        com.google.protobuf.RpcController controller,
        com.maxsam.pingpong.proto.Ping request)
        throws com.google.protobuf.ServiceException {
      return (com.maxsam.pingpong.proto.Pong) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.maxsam.pingpong.proto.Pong.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:PingPongService)
}

