// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.maxsam.pingpong.proto;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>required string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
