// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.maxsam.pingpong.proto;

/**
 * Protobuf type {@code RequestInfo}
 */
public final class RequestInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RequestInfo)
    RequestInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestInfo.newBuilder() to construct.
  private RequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestInfo() {
    errorText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            requestId_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            failed_ = input.readBool();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            cancelled_ = input.readBool();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            errorText_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.maxsam.pingpong.proto.Pingpong.internal_static_RequestInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.maxsam.pingpong.proto.Pingpong.internal_static_RequestInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.maxsam.pingpong.proto.RequestInfo.class, com.maxsam.pingpong.proto.RequestInfo.Builder.class);
  }

  private int bitField0_;
  public static final int REQUESTID_FIELD_NUMBER = 1;
  private int requestId_;
  /**
   * <code>required int32 requestId = 1;</code>
   * @return Whether the requestId field is set.
   */
  @java.lang.Override
  public boolean hasRequestId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 requestId = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public int getRequestId() {
    return requestId_;
  }

  public static final int FAILED_FIELD_NUMBER = 2;
  private boolean failed_;
  /**
   * <code>required bool failed = 2;</code>
   * @return Whether the failed field is set.
   */
  @java.lang.Override
  public boolean hasFailed() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required bool failed = 2;</code>
   * @return The failed.
   */
  @java.lang.Override
  public boolean getFailed() {
    return failed_;
  }

  public static final int CANCELLED_FIELD_NUMBER = 3;
  private boolean cancelled_;
  /**
   * <code>required bool cancelled = 3;</code>
   * @return Whether the cancelled field is set.
   */
  @java.lang.Override
  public boolean hasCancelled() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required bool cancelled = 3;</code>
   * @return The cancelled.
   */
  @java.lang.Override
  public boolean getCancelled() {
    return cancelled_;
  }

  public static final int ERRORTEXT_FIELD_NUMBER = 4;
  private volatile java.lang.Object errorText_;
  /**
   * <code>required string errorText = 4;</code>
   * @return Whether the errorText field is set.
   */
  @java.lang.Override
  public boolean hasErrorText() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required string errorText = 4;</code>
   * @return The errorText.
   */
  @java.lang.Override
  public java.lang.String getErrorText() {
    java.lang.Object ref = errorText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        errorText_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string errorText = 4;</code>
   * @return The bytes for errorText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorTextBytes() {
    java.lang.Object ref = errorText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasRequestId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasFailed()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCancelled()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasErrorText()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, requestId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, failed_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(3, cancelled_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorText_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, requestId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, failed_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, cancelled_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorText_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.maxsam.pingpong.proto.RequestInfo)) {
      return super.equals(obj);
    }
    com.maxsam.pingpong.proto.RequestInfo other = (com.maxsam.pingpong.proto.RequestInfo) obj;

    if (hasRequestId() != other.hasRequestId()) return false;
    if (hasRequestId()) {
      if (getRequestId()
          != other.getRequestId()) return false;
    }
    if (hasFailed() != other.hasFailed()) return false;
    if (hasFailed()) {
      if (getFailed()
          != other.getFailed()) return false;
    }
    if (hasCancelled() != other.hasCancelled()) return false;
    if (hasCancelled()) {
      if (getCancelled()
          != other.getCancelled()) return false;
    }
    if (hasErrorText() != other.hasErrorText()) return false;
    if (hasErrorText()) {
      if (!getErrorText()
          .equals(other.getErrorText())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestId()) {
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
    }
    if (hasFailed()) {
      hash = (37 * hash) + FAILED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFailed());
    }
    if (hasCancelled()) {
      hash = (37 * hash) + CANCELLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCancelled());
    }
    if (hasErrorText()) {
      hash = (37 * hash) + ERRORTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getErrorText().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.maxsam.pingpong.proto.RequestInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.maxsam.pingpong.proto.RequestInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestInfo)
      com.maxsam.pingpong.proto.RequestInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.maxsam.pingpong.proto.Pingpong.internal_static_RequestInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.maxsam.pingpong.proto.Pingpong.internal_static_RequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.maxsam.pingpong.proto.RequestInfo.class, com.maxsam.pingpong.proto.RequestInfo.Builder.class);
    }

    // Construct using com.maxsam.pingpong.proto.RequestInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      failed_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      cancelled_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      errorText_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.maxsam.pingpong.proto.Pingpong.internal_static_RequestInfo_descriptor;
    }

    @java.lang.Override
    public com.maxsam.pingpong.proto.RequestInfo getDefaultInstanceForType() {
      return com.maxsam.pingpong.proto.RequestInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.maxsam.pingpong.proto.RequestInfo build() {
      com.maxsam.pingpong.proto.RequestInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.maxsam.pingpong.proto.RequestInfo buildPartial() {
      com.maxsam.pingpong.proto.RequestInfo result = new com.maxsam.pingpong.proto.RequestInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.failed_ = failed_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cancelled_ = cancelled_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.errorText_ = errorText_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.maxsam.pingpong.proto.RequestInfo) {
        return mergeFrom((com.maxsam.pingpong.proto.RequestInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.maxsam.pingpong.proto.RequestInfo other) {
      if (other == com.maxsam.pingpong.proto.RequestInfo.getDefaultInstance()) return this;
      if (other.hasRequestId()) {
        setRequestId(other.getRequestId());
      }
      if (other.hasFailed()) {
        setFailed(other.getFailed());
      }
      if (other.hasCancelled()) {
        setCancelled(other.getCancelled());
      }
      if (other.hasErrorText()) {
        bitField0_ |= 0x00000008;
        errorText_ = other.errorText_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasRequestId()) {
        return false;
      }
      if (!hasFailed()) {
        return false;
      }
      if (!hasCancelled()) {
        return false;
      }
      if (!hasErrorText()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.maxsam.pingpong.proto.RequestInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.maxsam.pingpong.proto.RequestInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int requestId_ ;
    /**
     * <code>required int32 requestId = 1;</code>
     * @return Whether the requestId field is set.
     */
    @java.lang.Override
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 requestId = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>required int32 requestId = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(int value) {
      bitField0_ |= 0x00000001;
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 requestId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = 0;
      onChanged();
      return this;
    }

    private boolean failed_ ;
    /**
     * <code>required bool failed = 2;</code>
     * @return Whether the failed field is set.
     */
    @java.lang.Override
    public boolean hasFailed() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bool failed = 2;</code>
     * @return The failed.
     */
    @java.lang.Override
    public boolean getFailed() {
      return failed_;
    }
    /**
     * <code>required bool failed = 2;</code>
     * @param value The failed to set.
     * @return This builder for chaining.
     */
    public Builder setFailed(boolean value) {
      bitField0_ |= 0x00000002;
      failed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool failed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      failed_ = false;
      onChanged();
      return this;
    }

    private boolean cancelled_ ;
    /**
     * <code>required bool cancelled = 3;</code>
     * @return Whether the cancelled field is set.
     */
    @java.lang.Override
    public boolean hasCancelled() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bool cancelled = 3;</code>
     * @return The cancelled.
     */
    @java.lang.Override
    public boolean getCancelled() {
      return cancelled_;
    }
    /**
     * <code>required bool cancelled = 3;</code>
     * @param value The cancelled to set.
     * @return This builder for chaining.
     */
    public Builder setCancelled(boolean value) {
      bitField0_ |= 0x00000004;
      cancelled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool cancelled = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCancelled() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cancelled_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object errorText_ = "";
    /**
     * <code>required string errorText = 4;</code>
     * @return Whether the errorText field is set.
     */
    public boolean hasErrorText() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string errorText = 4;</code>
     * @return The errorText.
     */
    public java.lang.String getErrorText() {
      java.lang.Object ref = errorText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorText_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string errorText = 4;</code>
     * @return The bytes for errorText.
     */
    public com.google.protobuf.ByteString
        getErrorTextBytes() {
      java.lang.Object ref = errorText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string errorText = 4;</code>
     * @param value The errorText to set.
     * @return This builder for chaining.
     */
    public Builder setErrorText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      errorText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string errorText = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorText() {
      bitField0_ = (bitField0_ & ~0x00000008);
      errorText_ = getDefaultInstance().getErrorText();
      onChanged();
      return this;
    }
    /**
     * <code>required string errorText = 4;</code>
     * @param value The bytes for errorText to set.
     * @return This builder for chaining.
     */
    public Builder setErrorTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      errorText_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RequestInfo)
  }

  // @@protoc_insertion_point(class_scope:RequestInfo)
  private static final com.maxsam.pingpong.proto.RequestInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.maxsam.pingpong.proto.RequestInfo();
  }

  public static com.maxsam.pingpong.proto.RequestInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestInfo>
      PARSER = new com.google.protobuf.AbstractParser<RequestInfo>() {
    @java.lang.Override
    public RequestInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.maxsam.pingpong.proto.RequestInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

