// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.maxsam.pingpong.proto;

public interface ServiceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string methodName = 1;</code>
   * @return Whether the methodName field is set.
   */
  boolean hasMethodName();
  /**
   * <code>required string methodName = 1;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>required string methodName = 1;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>required .RequestInfo status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .RequestInfo status = 2;</code>
   * @return The status.
   */
  com.maxsam.pingpong.proto.RequestInfo getStatus();
  /**
   * <code>required .RequestInfo status = 2;</code>
   */
  com.maxsam.pingpong.proto.RequestInfoOrBuilder getStatusOrBuilder();

  /**
   * <code>required bytes payload = 3;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>required bytes payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
